---
all:
  hosts:
  children:
    control_srv:
      hosts:
        control:
          ansibe_user: root
          ansible_host: 10.1.1.10
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
    gpu:
      hosts:
        gpu01:
          ansibe_user: root
          ansible_host: 10.1.1.11
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
        gpu02:
          ansibe_user: root
          ansible_host: 10.1.1.12
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
        gpu03:
          ansibe_user: root
          ansible_host: 10.1.1.13
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
        gpu04:
          ansibe_user: root
          ansible_host: 10.1.1.14
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
        gpu05:
          ansibe_user: root
          ansible_host: 10.1.1.15
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
        gpu06:
          ansibe_user: root
          ansible_host: 10.1.1.16
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
        gpu07:
          ansibe_user: root
          ansible_host: 10.1.1.17
          ansible_port: 22
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3


