---

- include: includes/host_dir.yaml

- name: push server info
  shell: "dmidecode > {{ temp_report }}"

- name: "grab file from test machine"
  ansible.builtin.fetch:
    src: '{{ temp_report }}'
    dest: '{{ local_report }}'
    flat: yes
