---

- import: host_dir.yaml

- name: "check if iperf3 is running"
  shell: 'ps ax | grep iperf3 | grep -v grep | wc -l'
  register: iperf_srv_status
  delegate_to: localhost

- name: "run iperf server if its not running"
  shell: 'iperf3 -s -D'
  when: iperf_srv_status.stdout == "0"
  delegate_to: localhost

- name: "create empty test result file"
  shell: "date > {{ temp_report }} && echo -------------- >> {{ temp_report }}"

- name: "iperf test 1"
  shell: "iperf3 -c 10.1.1.10 -f K >> {{ temp_report }}"

- name: "download report file from test machine"
  ansible.builtin.fetch:
    src: '{{ temp_report }}'
    dest: '/var/www/html/{{ inventory_hostname }}/network-speedtest-{{ inventory_hostname }}.txt'
    flat: yes


