---

- include: includes/host_dir.yaml

- include: includes/test_date.yaml

- name: "header"
  shell: "echo '' >> {{ temp_report }} && echo 'hdparm test' >> {{ temp_report }} && echo '' >> {{ temp_report }}"

- name: "disk test 1"
  shell: "hdparm -Tt /dev/sda >> {{ temp_report }}"

- name: "header"
  shell: "echo '' >> {{ temp_report }} && echo 'hdparm test direct access'  >> {{ temp_report }} && echo '--------------' >> {{ temp_report }}"

- name: "disk test 2"
  shell: "hdparm -Tt --direct /dev/sda >> {{ temp_report }}"

    #- name: "header"
    #  shell: "echo 'fio test'  > {{ temp_report }} && echo '--------------' >> {{ temp_report }}"

    #- name: "disk test 2"
    #  shell: "fio --name=random-write --ioengine=posixaio --rw=randwrite --bs=4k --numjobs=1 --size=1g --iodepth=1 --runtime=60 --time_based --end_fsync=1 >> {{ temp_report }}"

- include: includes/download_report.yaml

